{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "goalixa-auth.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgres.auth.password }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | b64enc }}
  {{- else }}
  POSTGRES_PASSWORD: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  POSTGRES_USER: {{ .Values.postgres.auth.username | b64enc }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | b64enc }}
{{- end }}
